outfile:main.o add.o add.o print.o save.o read.o count.o rev.o del.o search.o
	cc main.o add.o print.o save.o read.o count.o rev.o del.o search.o -o outfile
main.o:main.c
	cc -c main.c
add.o:add.c
	cc -c add.c
print.o:print.c
	cc -c print.c
save.o:save.c
	cc -c save.c
read.o:read.c
	cc -c read.c
count.o:count.c
	cc -c count.c
rev.o:rev.c
	cc -c rev.c
del.o:del.c
	cc -c del.c
search.o:search.c
	cc -c search.c
