rinkesh:main.o read.o add.o print.o save.o count.o rev.o del.o
	cc main.o read.o add.o print.o save.o count.o rev.o del.o -o rinkesh
main.o:main.c
	cc -c main.c
read.o:read.c
	cc -c read.c
add.o:add.c
	cc -c add.c
print.o:print.c
	cc -c print.c
save.o:save.c
	cc -c save.c
count.o:count.c
	cc -c count.c
rev.o:rev.c
	cc -c rev.c
del.o:del.c
	cc -c del.c
